# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{ modulesPath, ... }:

{
  imports = [
    # Include the default incus configuration.
    "${modulesPath}/virtualisation/incus-virtual-machine.nix"
    # Include the container-specific autogenerated configuration.
    ../../bundles/proxy
  ];

  customization = {
    user.name = "nixos";
    hostname = "nixos-dockge";
  };

  system.stateVersion = "25.11"; # Did you read the comment?
}
